"""creating table school

Revision ID: 486471827eef
Revises: bb46d23f1044
Create Date: 2024-11-01 11:45:18.274521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486471827eef'
down_revision = 'bb46d23f1044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolname', sa.String(length=50), nullable=False),
    sa.Column('schooladdress', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schoolname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
